language : python
python:
    - "3.6.3"

service:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE test_stackoverflow;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'test123';" -U postgres


install:
  - pip install -r requirements.txt
  - pip install coveralls


script: 
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=app

after_script:
  - coveralls

  